/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package version2;

import ConfigWindows.Properties;
import LoadingScreen.Loading;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import version2.Painting.Brush;

/**
 *
 * @author marcos
 */
public class MainWindow extends javax.swing.JFrame {
    private Loading loadingWindow;    
    private Properties propertiesWindow;
    private Painting painting;
    private RecentDocuments recentWindow;
    private SaveProject saveWindow;
    private UselessWindow uselessWindow;
    
    private Timer t;
    private ImageIcon savedIcon, unsavedIcon;
    private boolean changed = false;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        loadingWindow = new Loading(this);
        propertiesWindow = new Properties(this);
        painting = (Painting)jPanel1;
        recentWindow = new RecentDocuments(this);
        saveWindow = new SaveProject(this);
        uselessWindow = new UselessWindow(this);
        
        t = new Timer();
        TimerTask tt;
        tt = new TimerTask() {
            @Override
            public void run() {
                java.awt.EventQueue.invokeLater(() -> {
                    loadingWindow.load();
                    
                    if(loadingWindow.finished())
                        stopLoading();
                });
            }
        };
        
        t.schedule(tt, 0, 10);
        
        unsavedIcon = new ImageIcon(getClass().getResource("/save.png"));
        savedIcon = new ImageIcon(getClass().getResource("/unsaved.png"));
        
        jButton6.setBackground(painting.getColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Painting(this);
        jToolBar1 = new javax.swing.JToolBar();
        Button_RectStroke = new javax.swing.JButton();
        Button_FillRect = new javax.swing.JButton();
        Button_OvalStroke = new javax.swing.JButton();
        Button_OvalFill = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        Button_SaveProject = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        Button_ColorBlack = new javax.swing.JButton();
        Button_ColorWhite = new javax.swing.JButton();
        Button_ColorDarkRed = new javax.swing.JButton();
        Button_ColorRed = new javax.swing.JButton();
        Button_ColorMustard = new javax.swing.JButton();
        Button_ColorYellow = new javax.swing.JButton();
        Button_ColorDarkGreen = new javax.swing.JButton();
        Button_ColorLightBlue = new javax.swing.JButton();
        Button_ColorDarkBlue = new javax.swing.JButton();
        Button_ColorBlue = new javax.swing.JButton();
        Button_ColorPurple = new javax.swing.JButton();
        Button_ColorPink = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        Button_Useless = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Menu_Open = new javax.swing.JMenuItem();
        Menu_OpenRecent = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Menu_SaveAs = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        Menu_Save = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        Button_RectStroke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RectStroke.png"))); // NOI18N
        Button_RectStroke.setToolTipText("Rectangle outline");
        Button_RectStroke.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_RectStroke.setFocusable(false);
        Button_RectStroke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_RectStroke.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_RectStroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RectStrokeActionPerformed(evt);
            }
        });
        jToolBar1.add(Button_RectStroke);

        Button_FillRect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FilleRectpng.png"))); // NOI18N
        Button_FillRect.setToolTipText("Filled rectangle");
        Button_FillRect.setFocusable(false);
        Button_FillRect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_FillRect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_FillRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_FillRectActionPerformed(evt);
            }
        });
        jToolBar1.add(Button_FillRect);

        Button_OvalStroke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CircleStroke.png"))); // NOI18N
        Button_OvalStroke.setToolTipText("Oval outline");
        Button_OvalStroke.setFocusable(false);
        Button_OvalStroke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_OvalStroke.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_OvalStroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_OvalStrokeActionPerformed(evt);
            }
        });
        jToolBar1.add(Button_OvalStroke);

        Button_OvalFill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CircleFill.png"))); // NOI18N
        Button_OvalFill.setToolTipText("Filled oval");
        Button_OvalFill.setFocusable(false);
        Button_OvalFill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_OvalFill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_OvalFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_OvalFillActionPerformed(evt);
            }
        });
        jToolBar1.add(Button_OvalFill);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Line.png"))); // NOI18N
        jButton5.setToolTipText("Straight line");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HandDraw.png"))); // NOI18N
        jButton4.setToolTipText("Hand draw (free draw)");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ColorPallete.png"))); // NOI18N
        jButton6.setToolTipText("Color picker");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setOpaque(true);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        Button_SaveProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        Button_SaveProject.setToolTipText("Save file");
        Button_SaveProject.setEnabled(false);
        Button_SaveProject.setFocusable(false);
        Button_SaveProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_SaveProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_SaveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SaveProjectActionPerformed(evt);
            }
        });
        jToolBar2.add(Button_SaveProject);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/export.png"))); // NOI18N
        jButton2.setToolTipText("Export image");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButton3.setToolTipText("Delete drawing");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        jSeparator1.setMaximumSize(new java.awt.Dimension(20, 12));
        jSeparator1.setPreferredSize(new java.awt.Dimension(20, 12));
        jToolBar2.add(jSeparator1);

        jLabel1.setText("Current stroke width: 1pt.");

        jSlider1.setToolTipText("Stroke width");
        jSlider1.setValue(1);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );

        jToolBar2.add(jPanel2);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setAlignmentY(0.0F);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 221));

        Button_ColorBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect815.png"))); // NOI18N
        Button_ColorBlack.setBorder(null);
        Button_ColorBlack.setBorderPainted(false);
        Button_ColorBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorBlackActionPerformed(evt);
            }
        });

        Button_ColorWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect817.png"))); // NOI18N
        Button_ColorWhite.setBorder(null);
        Button_ColorWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorWhiteActionPerformed(evt);
            }
        });

        Button_ColorDarkRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect819.png"))); // NOI18N
        Button_ColorDarkRed.setBorder(null);
        Button_ColorDarkRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorDarkRedActionPerformed(evt);
            }
        });

        Button_ColorRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect821.png"))); // NOI18N
        Button_ColorRed.setBorder(null);
        Button_ColorRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorRedActionPerformed(evt);
            }
        });

        Button_ColorMustard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect823.png"))); // NOI18N
        Button_ColorMustard.setBorder(null);
        Button_ColorMustard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorMustardActionPerformed(evt);
            }
        });

        Button_ColorYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect825.png"))); // NOI18N
        Button_ColorYellow.setBorder(null);
        Button_ColorYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorYellowActionPerformed(evt);
            }
        });

        Button_ColorDarkGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect827.png"))); // NOI18N
        Button_ColorDarkGreen.setBorder(null);
        Button_ColorDarkGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorDarkGreenActionPerformed(evt);
            }
        });

        Button_ColorLightBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect829.png"))); // NOI18N
        Button_ColorLightBlue.setBorder(null);
        Button_ColorLightBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorLightBlueActionPerformed(evt);
            }
        });

        Button_ColorDarkBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect815b.png"))); // NOI18N
        Button_ColorDarkBlue.setBorder(null);
        Button_ColorDarkBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorDarkBlueActionPerformed(evt);
            }
        });

        Button_ColorBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect817b.png"))); // NOI18N
        Button_ColorBlue.setBorder(null);
        Button_ColorBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorBlueActionPerformed(evt);
            }
        });

        Button_ColorPurple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect819b.png"))); // NOI18N
        Button_ColorPurple.setBorder(null);
        Button_ColorPurple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorPurpleActionPerformed(evt);
            }
        });

        Button_ColorPink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rect821b.png"))); // NOI18N
        Button_ColorPink.setBorder(null);
        Button_ColorPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ColorPinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_ColorBlack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorWhite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorDarkRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorMustard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorYellow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorDarkGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorLightBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorDarkBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorPurple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ColorPink)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_ColorDarkBlue)
                        .addComponent(Button_ColorBlue)
                        .addComponent(Button_ColorPurple)
                        .addComponent(Button_ColorPink))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button_ColorWhite)
                        .addComponent(Button_ColorDarkRed)
                        .addComponent(Button_ColorRed)
                        .addComponent(Button_ColorMustard)
                        .addComponent(Button_ColorBlack)
                        .addComponent(Button_ColorYellow)
                        .addComponent(Button_ColorDarkGreen)
                        .addComponent(Button_ColorLightBlue)))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jToolBar2.add(jScrollPane1);
        jToolBar2.add(jSeparator6);

        Button_Useless.setBackground(new java.awt.Color(144, 0, 0));
        Button_Useless.setForeground(new java.awt.Color(254, 254, 254));
        Button_Useless.setText("Useless button");
        Button_Useless.setFocusable(false);
        Button_Useless.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Useless.setOpaque(true);
        Button_Useless.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Button_Useless.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_UselessActionPerformed(evt);
            }
        });
        jToolBar2.add(Button_Useless);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 30));
        jToolBar2.add(jLabel2);

        jMenu1.setText("File");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("New");
        jMenu1.add(jMenuItem3);

        Menu_Open.setText("Open...");
        Menu_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Open);

        Menu_OpenRecent.setText("Open recent");
        Menu_OpenRecent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_OpenRecentActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_OpenRecent);
        jMenu1.add(jSeparator3);

        Menu_SaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Menu_SaveAs.setText("Save");
        Menu_SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_SaveAsActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_SaveAs);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Save as...");
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator2);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Export as...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenu4.setText("Import");

        jMenuItem7.setText("Image");
        jMenu4.add(jMenuItem7);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator4);

        Menu_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Save.setText("Properties...");
        Menu_Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu_SaveMousePressed(evt);
            }
        });
        jMenu1.add(Menu_Save);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Undo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_SaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_SaveMousePressed
        propertiesWindow.setVisible(true);
        propertiesWindow.setLastBgColor(painting.getBackground());
    }//GEN-LAST:event_Menu_SaveMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        painting.mousePressed(evt.getX(), evt.getY());
        painting.repaint();
        this.changeMade();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        try{
        painting.mouseReleased(evt.getX(), evt.getY());
        painting.repaint();
        }catch(NullPointerException e){}
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        try{
            painting.mouseDragged(evt.getX(), evt.getY());
            painting.repaint();
        }catch(NullPointerException e){}
    }//GEN-LAST:event_jPanel1MouseDragged

    private void Button_RectStrokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RectStrokeActionPerformed
        painting.setBrush(Brush.RECT_STROKE);
    }//GEN-LAST:event_Button_RectStrokeActionPerformed

    private void Button_FillRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_FillRectActionPerformed
       painting.setBrush(Brush.RECT_FILL);
    }//GEN-LAST:event_Button_FillRectActionPerformed

    private void Button_OvalStrokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_OvalStrokeActionPerformed
        painting.setBrush(Brush.OVAL_STROKE);
    }//GEN-LAST:event_Button_OvalStrokeActionPerformed

    private void Button_OvalFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_OvalFillActionPerformed
        painting.setBrush(Brush.OVAL_FILL);
    }//GEN-LAST:event_Button_OvalFillActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Color c = JColorChooser.showDialog(null, "Choose the color", painting.getColor());
        
        changeColor(c);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        saveImage();        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        saveImage();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        painting.setBrush(Brush.STRAIGHT_LINE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        painting.deleteEverything();
        painting.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        painting.setBrush(Brush.HANDDRAWN_LINE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        painting.undo();
        painting.repaint();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        painting.setStrokeWidth(jSlider1.getValue());
        jLabel1.setText("Current stroke width: " + jSlider1.getValue() + "pt.");
    }//GEN-LAST:event_jSlider1StateChanged

    private void Button_SaveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SaveProjectActionPerformed
        saveWindow.setVisible(true);
    }//GEN-LAST:event_Button_SaveProjectActionPerformed

    private void Menu_SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_SaveAsActionPerformed
        saveWindow.setVisible(true);
    }//GEN-LAST:event_Menu_SaveAsActionPerformed

    private void Button_ColorBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorBlackActionPerformed
        changeColor(Color.BLACK);
    }//GEN-LAST:event_Button_ColorBlackActionPerformed

    private void Button_ColorWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorWhiteActionPerformed
        changeColor(Color.WHITE);
    }//GEN-LAST:event_Button_ColorWhiteActionPerformed

    private void Button_ColorDarkRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorDarkRedActionPerformed
        changeColor(new Color(150, 0, 0));
    }//GEN-LAST:event_Button_ColorDarkRedActionPerformed

    private void Button_ColorRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorRedActionPerformed
        changeColor(Color.RED);
    }//GEN-LAST:event_Button_ColorRedActionPerformed

    private void Button_ColorMustardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorMustardActionPerformed
        changeColor(new Color(204, 146, 0));
    }//GEN-LAST:event_Button_ColorMustardActionPerformed

    private void Button_ColorYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorYellowActionPerformed
        changeColor(Color.YELLOW);
    }//GEN-LAST:event_Button_ColorYellowActionPerformed

    private void Button_ColorDarkGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorDarkGreenActionPerformed
        changeColor(Color.GREEN);
    }//GEN-LAST:event_Button_ColorDarkGreenActionPerformed

    private void Button_ColorLightBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorLightBlueActionPerformed
        changeColor(new Color(0, 156, 114));
    }//GEN-LAST:event_Button_ColorLightBlueActionPerformed

    private void Button_ColorDarkBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorDarkBlueActionPerformed
        changeColor(new Color(6, 0, 94));
    }//GEN-LAST:event_Button_ColorDarkBlueActionPerformed

    private void Button_ColorBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorBlueActionPerformed
        changeColor(Color.BLUE);
    }//GEN-LAST:event_Button_ColorBlueActionPerformed

    private void Button_ColorPurpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorPurpleActionPerformed
        changeColor(new Color(66, 0, 94));
    }//GEN-LAST:event_Button_ColorPurpleActionPerformed

    private void Button_ColorPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ColorPinkActionPerformed
        changeColor(Color.PINK);
    }//GEN-LAST:event_Button_ColorPinkActionPerformed

    public void changeColor(Color c){
        painting.changeColor(c);    
        jButton6.setBackground(c);
        saveWindow.changeColor(c);
    }
    
    private void Menu_OpenRecentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_OpenRecentActionPerformed
        recentWindow.setVisible(true);
    }//GEN-LAST:event_Menu_OpenRecentActionPerformed

    private void Menu_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_OpenActionPerformed
        loadProject();
    }//GEN-LAST:event_Menu_OpenActionPerformed

    private void Button_UselessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_UselessActionPerformed
        uselessWindow.setVisible(true);
    }//GEN-LAST:event_Button_UselessActionPerformed

    public void saveImage(){
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
        chooser.setFileFilter(filter);
        chooser.setApproveButtonText("Save");
        
        int returnVal = chooser.showOpenDialog(this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION) {
           BufferedImage b = new BufferedImage(painting.getWidth(), painting.getHeight(), BufferedImage.TYPE_INT_ARGB);
           Graphics g = b.createGraphics();
           painting.paint(g);
           g.dispose();
           
           try{
               System.out.println(chooser.getSelectedFile().getAbsolutePath() + ".png");
                File newImg = new File(chooser.getSelectedFile().getAbsolutePath() + ".png");
                if(newImg.exists()){
                    int option = JOptionPane.showConfirmDialog(jMenu1, "The file already exists! Overwrite the file?", "File exists", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

                    if(option != JOptionPane.OK_OPTION)
                        throw new IOException();
                }
                
                ImageIO.write(b, "png", newImg);
                System.out.println("Image saved!");
                
                recentWindow.addFile(newImg);
           }catch(IOException e){}
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(false);
        });
    }
    
    public void stopLoading(){
        t.cancel();
        this.setVisible(true);
        loadingWindow.setVisible(false);
    }
    
    public void setPaintBackground(Color c){
        painting.setBackground(c);
        painting.repaint();
    }
    
    public void changeMade(){
        changed = true;
        Button_SaveProject.setEnabled(true);
    }
    
    public void changeSaved(){
        changed = false;
        Button_SaveProject.setEnabled(false);
    }
    
    public void saveProject(){
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Paint 2.0 files", "p2");
        chooser.setFileFilter(filter);
        chooser.setApproveButtonText("Save");
        
        int returnVal = chooser.showOpenDialog(this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            try{
                File oFile = new File(chooser.getSelectedFile().getAbsolutePath() + ".p2");
           
                System.out.println(chooser.getSelectedFile().getAbsolutePath() + ".p2");
                if(oFile.exists()){
                    int option = JOptionPane.showConfirmDialog(jMenu1, "The file already exists! Overwrite the file?", "File exists", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

                    if(option != JOptionPane.OK_OPTION)
                        throw new IOException();
                }
                
                try (ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream(oFile))) {
                    output.writeObject(painting);
                    output.close();
                }
                
                
                System.out.println("Image saved!");
                
                recentWindow.addFile(oFile);
           }catch(IOException e){}
        }
    }
    
    public void loadProject(){
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Paint 2.0 files", "p2");
        chooser.setFileFilter(filter);
        
        int returnVal = chooser.showOpenDialog(this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            try{
                File oFile = new File(chooser.getSelectedFile().getAbsolutePath());
           
                System.out.println(chooser.getSelectedFile().getAbsolutePath());
                
                if(!oFile.exists()){
                    JOptionPane.showMessageDialog(jMenu1, "The selected file is not a project", "Not a project", JOptionPane.OK_OPTION);
                    throw new IOException();
                }
                
                try (ObjectInputStream input = new ObjectInputStream(new FileInputStream(oFile))) {
                    painting = (Painting)input.readObject();
                    input.close();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                System.out.println("Image saved!");
                
                recentWindow.addFile(oFile);
                painting.repaint();
                System.out.println(painting.getNumberShapes());
           }catch(IOException e){
               System.out.println("Error loading project!");
               e.printStackTrace();
           }
        }
    }
    
    public void setUselessText(String str){
        jLabel2.setText(str);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ColorBlack;
    private javax.swing.JButton Button_ColorBlue;
    private javax.swing.JButton Button_ColorDarkBlue;
    private javax.swing.JButton Button_ColorDarkGreen;
    private javax.swing.JButton Button_ColorDarkRed;
    private javax.swing.JButton Button_ColorLightBlue;
    private javax.swing.JButton Button_ColorMustard;
    private javax.swing.JButton Button_ColorPink;
    private javax.swing.JButton Button_ColorPurple;
    private javax.swing.JButton Button_ColorRed;
    private javax.swing.JButton Button_ColorWhite;
    private javax.swing.JButton Button_ColorYellow;
    private javax.swing.JButton Button_FillRect;
    private javax.swing.JButton Button_OvalFill;
    private javax.swing.JButton Button_OvalStroke;
    private javax.swing.JButton Button_RectStroke;
    private javax.swing.JButton Button_SaveProject;
    private javax.swing.JButton Button_Useless;
    private javax.swing.JMenuItem Menu_Open;
    private javax.swing.JMenuItem Menu_OpenRecent;
    private javax.swing.JMenuItem Menu_Save;
    private javax.swing.JMenuItem Menu_SaveAs;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables

    Painting getPainting() {
        return painting;
    }

    public RecentDocuments getRecentWindow() {
        return recentWindow;
    }
}
